api_key = "q0oCv1c15kXz5rxp6Tj70r2R7nrlxf034PZ85LDmZoNGw3hfU9cTWon609ArT2nx"
api_secret = "mGsY842HK1ciWuHA2YwOaQDUHFM0kKy7SwoXIuGdjLttyWzP9Bz15c4Cl0NDMXDu"


telegram_token = "7888476021:AAHUHmjmiQS46CS0RFtBFtYf1s511wzL9SM"
# chat_id = "1994074962" # Do BOT
chat_id = "-1002539037333" # do Grupo

#"message":{"message_id":3,"from":{"id":1994074962,"is_bot":false,"first_name":"Denis","last_name":"Valim","username":"DenisValim","language_code":"pt-br"},"chat":{"id":1994074962,"first_name":"Denis","last_name":"Valim","username":"DenisValim","type":"private"},"date":1742678753,"text":"Ol\u00e1"}},{"update_id":516523631,
#"message":{"message_id":4,"from":{"id":1994074962,"is_bot":false,"first_name":"Denis","last_name":"Valim","username":"DenisValim","language_code":"pt-br"},"chat":{"id":1994074962,"first_name":"Denis","last_name":"Valim","username":"DenisValim","type":"private"},"date":1742678759,"text":"Tudo bem?"}}]}